# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cagent < Formula
  desc ""
  homepage "https://github.com/nomad10101/cloudback"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nomad10101/cloudback/releases/download/v0.0.5/cloudback_Darwin_x86_64.tar.gz"
      sha256 "6aa05671eb5748882c1567a482f88fae69a2c5de2323b987db71ead9daec69fc"

      def install
        bin.install "cloudback"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nomad10101/cloudback/releases/download/v0.0.5/cloudback_Darwin_arm64.tar.gz"
      sha256 "1a30071efbcfeaba122cef199784cd0ff6d92be4b31a82d9e89f337a26980097"

      def install
        bin.install "cloudback"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nomad10101/cloudback/releases/download/v0.0.5/cloudback_Linux_arm64.tar.gz"
      sha256 "d533156582e06279a03733919c408fadaab9cfd7c043f73de6e7836557714179"

      def install
        bin.install "cloudback"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nomad10101/cloudback/releases/download/v0.0.5/cloudback_Linux_x86_64.tar.gz"
      sha256 "151c3e4e3f4af26f486606c60afb8f7498e958e900ed72f69b873f5aee8d0bde"

      def install
        bin.install "cloudback"
      end
    end
  end
end
