# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class Cagent < Formula
  desc ""
  homepage "https://github.com/nomad10101/cloudback"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nomad10101/cloudback/releases/download/v0.0.6/cloudback_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d249930890dfa8b4de97d5f9cd9f1f61ce62add94d8e7702289b550f88225798"

      def install
        bin.install "cloudback"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nomad10101/cloudback/releases/download/v0.0.6/cloudback_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "36fd4c990fa619ca011b5ba150c1952b9f25345e6abd375c5ad1ef3f0fc47bf1"

      def install
        bin.install "cloudback"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nomad10101/cloudback/releases/download/v0.0.6/cloudback_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e036246c5e4992bc61b92785a314a0b16b9b50000226c7f93295bdd85d432ba3"

      def install
        bin.install "cloudback"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nomad10101/cloudback/releases/download/v0.0.6/cloudback_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c002708c44e7f81b006da673cf47e061efea26db51a1f6f8245d1559b7673bb4"

      def install
        bin.install "cloudback"
      end
    end
  end
end
