# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cagent < Formula
  desc ""
  homepage "https://github.com/nomad10101/cloudback"
  version "0.0.22"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nomad10101/portola-release/releases/download/v0.0.22/portola-release_Darwin_x86_64.tar.gz"
      sha256 "ec1311c34d597f70fdce7626dd1590001dac66f3c136d2b510da350e5f66a05f"

      def install
        bin.install "cagent"
        prefix.install Dir["assets"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nomad10101/portola-release/releases/download/v0.0.22/portola-release_Darwin_arm64.tar.gz"
      sha256 "6fd19d587eb37aa1509a97cf0f4bc0aa4399c9f0883f11ded52442491e6e366c"

      def install
        bin.install "cagent"
        prefix.install Dir["assets"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nomad10101/portola-release/releases/download/v0.0.22/portola-release_Linux_arm64.tar.gz"
      sha256 "d57029f6704fd7ae6002845ae5bea70f2785229d8ea5ceecd705623480e203e8"

      def install
        bin.install "cagent"
        prefix.install Dir["assets"]
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nomad10101/portola-release/releases/download/v0.0.22/portola-release_Linux_x86_64.tar.gz"
      sha256 "33f903eff976cfd5fe7872e1bcf822c25dcff7c520a9c7b6ff184e073e026239"

      def install
        bin.install "cagent"
        prefix.install Dir["assets"]
      end
    end
  end

  def caveats
    <<~EOS
      ****************************************************************
      Listen up...
      ****************************************************************
    EOS
  end
end
