# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cagent < Formula
  desc ""
  homepage "https://github.com/nomad10101/cloudback"
  version "0.0.36"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nomad10101/portola-release/releases/download/v0.0.36/portola-release_Darwin_arm64.tar.gz"
      sha256 "f7e87f8d813ed35621d071a60cbac6491570e38800fc5bbcdbf381e489022257"

      def install
        bin.install "cagent"
        prefix.install Dir["assets"]
        prefix.install_symlink Dir["assets"]
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nomad10101/portola-release/releases/download/v0.0.36/portola-release_Darwin_x86_64.tar.gz"
      sha256 "850b0fd3d5e4b337cb9cbbb949c4b342fa3bb3e6c4a521a35ba710f1c0ddf819"

      def install
        bin.install "cagent"
        prefix.install Dir["assets"]
        prefix.install_symlink Dir["assets"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nomad10101/portola-release/releases/download/v0.0.36/portola-release_Linux_arm64.tar.gz"
      sha256 "27e1c43faa70bd32897fa9fc87f3d67c998a8074f3bc5a3fb1cd46dacb6da0f4"

      def install
        bin.install "cagent"
        prefix.install Dir["assets"]
        prefix.install_symlink Dir["assets"]
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nomad10101/portola-release/releases/download/v0.0.36/portola-release_Linux_x86_64.tar.gz"
      sha256 "7767ff5ea2599ed0f693a0390135116adfecb1c9341c7a5957ff9eaadf4d06f4"

      def install
        bin.install "cagent"
        prefix.install Dir["assets"]
        prefix.install_symlink Dir["assets"]
      end
    end
  end

  def caveats
    <<~EOS
      ****************************************************************
      Listen up...
      ****************************************************************
    EOS
  end

  service do
    run [opt_bin/"cagent", "--assets-path", opt_prefix/"assets", "service"]
    environment_variables BREW_OPT_HOME: opt_prefix
    keep_alive true
  end
end
